In [1]:
import numpy as np
import scipy.integrate as si



In [2]:
w = np.array((50e-3, 7.5e-3, 90e-3))
h = np.array((12e-3, 70e-3, 10e-3))



In [34]:
 (a * y_c*1e9).sum() / (a * 1e6).sum()

52.62962962962962

In [3]:
a = w * h
a



array([0.0006  , 0.000525, 0.0009  ])

In [4]:
h_hi = h.cumsum()
h_lo = np.hstack((0, h_hi[:2]))
y_c = (h_hi + h_lo) * 0.5
y_c



array([0.006, 0.047, 0.087])

In [31]:
(a * y_c) .sum()

0.000106575

In [5]:
y_cent = sum(a * y_c) / sum(a)
y_cent



0.05262962962962963

In [6]:
h1_above_cent = h[1] + h[0] - y_cent
h1_above_cent



0.029370370370370373

In [7]:
h1_below_cent = y_cent - h[0]
h1_below_cent



0.04062962962962963

In [8]:
np.isclose( h1_above_cent + h1_below_cent, h[1])

True

Moment of the area 0 about the neutral axis

In [36]:
dist0 = y_cent + (-0.5) * h[0]
mom0 = dist0 * a[0]
mom0



2.797777777777778e-05

Moment of area1 below centroid about the centroid

In [39]:
dist_below = h1_below_cent * 0.5
area_below = (w[1] * h1_below_cent)
mom_below = dist_below * area_below
mom_below


6.190375514403291e-06

Moment of area1 above centroid about the centroid

In [40]:
dist_above = h1_above_cent * 0.5
area_above = (w[1] * h1_above_cent)
mom_above = dist_above * area_above
mom_above


3.234819958847737e-06

Moment of the area 2 about the neutral axis

In [37]:
dist2 = h[0] + h[1] + 0.5 * h[2] - y_cent
mom2 = dist2 * a[2]
mom2



3.093333333333334e-05

In [41]:
mom0 + mom_below

3.4168153292181075e-05

In [42]:
mom_above + mom2

3.4168153292181075e-05

In [13]:
y = np.array((
    0, h[0], h[0]+1e-6, h[0] + h[1], h[0] + h[1] + 1e-6, h.sum()
))
y


array([0.      , 0.012   , 0.012001, 0.082   , 0.082001, 0.092   ])

In [14]:
x = np.array((
    w[0], w[0], w[1], w[1], w[2], w[2]
))
x



array([0.05  , 0.05  , 0.0075, 0.0075, 0.09  , 0.09  ])

In [15]:
y_array = np.arange(0, h.sum(), 1e-5)
width_array = np.interp(y_array, y, x)



In [18]:
dy = y_array[1] - y_array[0]
dy



1e-05

In [19]:
da = dy * width_array



In [20]:
y_da = y_array * da



In [21]:
moment1 = y_da.sum()
moment1



0.00010650232500000002

In [22]:
y_centroid = moment1 / da.sum()
y_centroid



0.05260413168033193

In [24]:
y_cent - y_centroid



2.549794929770227e-05

In [25]:
da[y_array<y_centroid].sum()

0.0009050000000000004

In [26]:
da[y_array>y_centroid].sum()

0.0011196000000000001