In [1]:
import numpy as np
import scipy.integrate as si



In [2]:
w = np.array((0., 20e-3, 150e-3))
h = np.array((0, 200e-3, 20e-3))



In [3]:
a = w * h
a



array([0.   , 0.004, 0.003])

In [4]:
h_hi = h.cumsum()
h_lo = np.hstack((0, h_hi[:2]))
y_c = (h_hi + h_lo) * 0.5
y_c



array([0.  , 0.1 , 0.21])

In [5]:
(a * y_c) .sum()

0.00103

In [6]:
y_cent = sum(a * y_c) / sum(a)
y_cent



0.14714285714285716

In [13]:
y_cent * w[1]

0.0029428571428571433

In [16]:
(h[1] - y_cent) * w[1] + a[2]

0.004057142857142857

In [17]:
h[1], y_cent

(0.2, 0.14714285714285716)

In [7]:
h1_above_cent = h[1] + h[0] - y_cent
h1_above_cent



0.05285714285714285

In [8]:
h1_below_cent = y_cent - h[0]
h1_below_cent



0.14714285714285716

In [9]:
np.isclose( h1_above_cent + h1_below_cent, h[1])

True

In [10]:
a[0] + w[1] * h1_below_cent

0.0029428571428571433

In [11]:
a[1] + w[1] * h1_above_cent

0.005057142857142857

In [11]:
a[0] + w[1] * h1_above_cent

0.0008202777777777778

In [12]:
a[1] + w[1] * h1_below_cent

0.0008297222222222223

In [13]:
y = np.array((
    0, h[0], h[0]+1e-6, h[0] + h[1], h[0] + h[1] + 1e-6, h.sum()
))
y


array([0.      , 0.012   , 0.012001, 0.082   , 0.082001, 0.092   ])

In [14]:
x = np.array((
    w[0], w[0], w[1], w[1], w[2], w[2]
))
x



array([0.05  , 0.05  , 0.0075, 0.0075, 0.09  , 0.09  ])

In [15]:
y_array = np.arange(0, h.sum(), 1e-5)
width_array = np.interp(y_array, y, x)



In [18]:
dy = y_array[1] - y_array[0]
dy



1e-05

In [19]:
da = dy * width_array



In [20]:
y_da = y_array * da



In [21]:
moment1 = y_da.sum()
moment1



0.00010650232500000002

In [22]:
y_centroid = moment1 / da.sum()
y_centroid



0.05260413168033193

In [24]:
y_cent - y_centroid



2.549794929770227e-05

In [25]:
da[y_array<y_centroid].sum()

0.0009050000000000004

In [26]:
da[y_array>y_centroid].sum()

0.0011196000000000001